### ISSUE TITLE
Badges Collection

### ISSUE THREAD

**Issue by sanjaynetagal** [raagavardhini/Stepin-Employee-Record-System#3]
You have done a good work and do and collect remaining badges

**Comment by raagavardhini** [comment]
Thank You

**Comment by sanjaynetagal** [comment]
What's this?

**Comment by raagavardhini** [comment]
@sanjaynetagal You commented on my work for that I said thank you

**Comment by sanjaynetagal** [comment]
Oh OK ragavardhini
